import { GetStaticProps, InferGetStaticPropsType, NextPage } from 'next'
import Head from 'next/head'

import { DM_Sans as DMSans, Roboto } from 'next/font/google'

import { Card } from '@/components/Card'

import styles from '@/styles/Home.module.scss'
import Icon1 from '@/assets/icons/icon1'
import Icon2 from '@/assets/icons/icon2'
import Icon3 from '@/assets/icons/icon3'
import { Header } from '@/components/Header'
import { useQuery } from 'react-query'

const dmSans = DMSans({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ["400", "500", "700"] })

interface HomeProps {
  products: {
    id: string
    title: string
    image: string
    price: string
    score: string
  }[]
  total: number
}

const Home: NextPage<HomeProps> = ({
  products,
  total
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  const { data } = useQuery({
    initialData: {
      products,
      total
    },
    queryKey: ['products', 'total'],
    queryFn: async (): Promise<HomeProps> => {
      const { products, total } = await fetch('http://localhost:3333/api/product')
        .then((res) => res.json())
        .then((json) => json)

      return {
        products,
        total
      }
    }
  })

  return (
    <>
      <Head>
        <title>Halogenn - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.homeContainer} ${dmSans.className} ${roboto.className}`}>
        <Header />
        <main className={styles.main}>
          <section className={styles.aboutContainer}>
            <h2 className={styles.title}>Qualidade e expertise em produtos <span>químicos e acessórios</span></h2>
            <p>Estamos preparados para te entender e atender da melhor forma para suprir todas as suas demandas em químicos e similares.</p>
          </section>
          <section className={styles.bannerContainer}>
            <div>
              <h2>Produtos</h2>
              <div>
                <Icon1 />
                <span>Vidrarias e Equipamentos</span>
              </div>
            </div>
            <div>
              <h2>Químicos</h2>
              <div>
                <Icon2 />
                <span>Materiais Químicos</span>
              </div>
            </div>
            <div>
              <h2>Laboratórios</h2>
              <div>
                <Icon3 />
                <span>Ferramentas e utensílios</span>
              </div>
            </div>
          </section>
          <section className={styles.productsContainer}>
            <h2>PRODUTOS</h2>
            <div>
              {data?.products.map((product) => (
                <Card
                  key={product.id}
                  title={product.title}
                  image={product.image}
                  price={product.price}
                  score={product.score}
                />
              ))}
            </div>
          </section>
        </main>
      </div>
    </>
  )
}

export const getStaticProps: GetStaticProps<HomeProps> = async () => {
  const { products, total } = await fetch('http://localhost:3333/api/product')
    .then((res) => res.json())
    .then((json) => json)

  return {
    props: {
      products,
      total,
    },
  }
}

export default Home
